'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatFileSize } from '@/types/movie';
export function MovieFileTable({ files, onEdit, onDelete }) {
    if (files.length === 0) {
        return (_jsx("div", { className: "rounded-sm border border-border-subtle bg-surface-1 px-4 py-8 text-center", children: _jsx("p", { className: "text-text-secondary", children: "No movie files found" }) }));
    }
    return (_jsx("div", { className: "overflow-x-auto rounded-sm border border-border-subtle", children: _jsxs("table", { className: "min-w-full text-left text-sm", children: [_jsx("thead", { className: "bg-surface-2 text-text-secondary", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2", children: "Path" }), _jsx("th", { className: "px-4 py-2", children: "Quality" }), _jsx("th", { className: "px-4 py-2", children: "Size" }), _jsx("th", { className: "px-4 py-2", children: "Language" }), _jsx("th", { className: "px-4 py-2 text-right", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-border-subtle bg-surface-1", children: files.map(file => (_jsxs("tr", { className: "hover:bg-surface-2/50", children: [_jsx("td", { className: "px-4 py-2", children: _jsx("div", { className: "max-w-md truncate", title: file.path, children: file.path }) }), _jsx("td", { className: "px-4 py-2", children: _jsx("span", { className: "rounded-sm bg-surface-2 px-2 py-1 text-xs", children: file.quality }) }), _jsx("td", { className: "px-4 py-2", children: formatFileSize(file.size) }), _jsx("td", { className: "px-4 py-2", children: file.language }), _jsx("td", { className: "px-4 py-2 text-right", children: _jsxs("div", { className: "flex justify-end gap-1", children: [onEdit && (_jsx("button", { type: "button", className: "rounded-sm border border-border-subtle px-2 py-1 text-xs hover:bg-surface-2", onClick: () => onEdit(file), children: "Edit" })), onDelete && (_jsx("button", { type: "button", className: "rounded-sm border border-accent-danger/30 px-2 py-1 text-xs text-accent-danger hover:bg-accent-danger/10", onClick: () => onDelete(file), children: "Delete" }))] }) })] }, file.id))) })] }) }));
}
//# sourceMappingURL=MovieFileTable.js.map