'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ImportConfigPanel({ config, onChange, rootFolders }) {
    const updateConfig = (key, value) => {
        onChange({ ...config, [key]: value });
    };
    return (_jsxs("div", { className: "rounded-lg border border-border-subtle bg-surface-1 p-4", children: [_jsx("h3", { className: "text-base font-semibold", children: "Import Configuration" }), _jsx("p", { className: "mt-1 text-sm text-text-secondary", children: "These settings will be applied to all imported series." }), _jsxs("div", { className: "mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3", children: [_jsxs("label", { className: "space-y-1.5 text-sm", children: [_jsx("span", { className: "font-medium text-text-primary", children: "Quality Profile" }), _jsxs("select", { value: config.qualityProfileId, onChange: e => updateConfig('qualityProfileId', Number(e.target.value)), className: "w-full rounded-sm border border-border-subtle bg-surface-0 px-3 py-2", children: [_jsx("option", { value: 1, children: "HD-1080p" }), _jsx("option", { value: 2, children: "UltraHD-4K" }), _jsx("option", { value: 3, children: "Any" })] })] }), _jsxs("label", { className: "space-y-1.5 text-sm", children: [_jsx("span", { className: "font-medium text-text-primary", children: "Root Folder" }), _jsx("select", { value: config.rootFolder, onChange: e => updateConfig('rootFolder', e.target.value), className: "w-full rounded-sm border border-border-subtle bg-surface-0 px-3 py-2", children: rootFolders.length === 0 ? (_jsx("option", { value: "/media/tv", children: "/media/tv (default)" })) : (rootFolders.map(folder => (_jsx("option", { value: folder, children: folder }, folder)))) })] }), _jsxs("label", { className: "space-y-1.5 text-sm", children: [_jsx("span", { className: "font-medium text-text-primary", children: "Series Type" }), _jsxs("select", { value: config.seriesType, onChange: e => updateConfig('seriesType', e.target.value), className: "w-full rounded-sm border border-border-subtle bg-surface-0 px-3 py-2", children: [_jsx("option", { value: "standard", children: "Standard" }), _jsx("option", { value: "anime", children: "Anime" }), _jsx("option", { value: "daily", children: "Daily" })] })] })] }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-6", children: [_jsxs("label", { className: "inline-flex items-center gap-2 text-sm", children: [_jsx("input", { type: "checkbox", checked: config.monitored, onChange: e => updateConfig('monitored', e.target.checked) }), _jsx("span", { className: "text-text-primary", children: "Monitor Series" })] }), _jsxs("label", { className: "inline-flex items-center gap-2 text-sm", children: [_jsx("input", { type: "checkbox", checked: config.seasonFolder, onChange: e => updateConfig('seasonFolder', e.target.checked) }), _jsx("span", { className: "text-text-primary", children: "Use Season Folders" })] })] }), _jsxs("div", { className: "mt-4 space-y-1.5 text-sm", children: [_jsx("span", { className: "font-medium text-text-primary", children: "Monitor New Items" }), _jsx("div", { className: "flex flex-wrap gap-2", children: [
                            { value: 'all', label: 'All Episodes' },
                            { value: 'future', label: 'Future Episodes' },
                            { value: 'none', label: 'None' },
                        ].map(option => (_jsx("button", { type: "button", onClick: () => updateConfig('monitorNewItems', option.value), className: `rounded-sm border px-3 py-1.5 text-xs font-medium ${config.monitorNewItems === option.value
                                ? 'border-accent-primary bg-accent-primary/10 text-text-primary'
                                : 'border-border-subtle text-text-secondary hover:border-accent-primary/50'}`, children: option.label }, option.value))) })] })] }));
}
//# sourceMappingURL=ImportConfigPanel.js.map