import { type ApiHttpClientConfig } from './httpClient';
export declare function createApiClients(config?: ApiHttpClientConfig): {
    httpClient: any;
    mediaApi: any;
    releaseApi: any;
    torrentApi: any;
    importApi: any;
    indexerApi: any;
    applicationsApi: any;
    appProfilesApi: any;
    downloadClientApi: any;
    importListsApi: any;
    tagsApi: any;
    subtitleApi: any;
    subtitleBlacklistApi: any;
    subtitleHistoryApi: any;
    subtitleProvidersApi: any;
    subtitleWantedApi: any;
    activityApi: any;
    calendarApi: any;
    categorySettingsApi: any;
    collectionApi: any;
    discoverApi: any;
    filtersApi: any;
    blocklistApi: any;
    settingsApi: any;
    healthApi: any;
    notificationsApi: any;
    proxySettingsApi: any;
    systemApi: any;
    backupApi: any;
    logsApi: any;
    updatesApi: any;
    qualityProfileApi: any;
    customFormatApi: any;
    languageProfilesApi: any;
    wantedApi: any;
    movieApi: any;
    seriesApi: any;
    eventsApi: any;
};
export { ApiClientError, ContractViolationError } from './errors';
export { ApiHttpClient } from './httpClient';
export { routeMap } from './routeMap';
export type { SubtitleVariantInventory, ManualSearchCandidate, SubtitleTrack, EpisodeSubtitle, SeriesSubtitleVariant, SeriesSyncResult, DiskScanResult, SubtitleSearchResult, BulkUpdateMoviesResult, BulkUpdateMoviesInput, SubtitleUploadRecord, SubtitleUploadInput, } from './subtitleApi';
export type { ManualSearchInput, ManualDownloadInput } from './subtitleApi';
export type { BlacklistedSubtitle, BlacklistOperationResult, BlacklistQueryParams, } from './subtitleBlacklistApi';
export type { SubtitleHistoryEntry, HistoryQueryParams, HistoryStats, StatsQueryParams, } from './subtitleHistoryApi';
export type { WantedSeriesEntry, WantedMovieEntry, WantedCount, WantedQueryParams, SearchTriggerResult, SeriesItemSearchResult, MovieItemSearchResult, } from './subtitleWantedApi';
export type { SubtitleProvider, ProviderSettings, ProviderTestResult, } from './subtitleProvidersApi';
export type { LanguageProfile, LanguageSetting, LanguageProfileInput, LanguageSettingInput, } from './languageProfilesApi';
export type { MovieCollection, CollectionMovie, CollectionEditForm } from './collectionApi';
export type { DiscoverMovie, DiscoverRecommendationsParams } from './discoverApi';
export type { DetectedSeries, SeriesSearchResult, ImportSeriesRequest, ScanFolderRequest, } from './importApi';
export type { MissingMovie, CutoffUnmetMovie } from './wantedApi';
export type { Movie, UpdateMovieInput } from './movieApi';
export type { Series, BulkSeriesChanges, BulkUpdateResult } from './seriesApi';
export type { CustomFilter, FilterCondition, FilterConditionsGroup } from './filters';
export type { ProxySettingsItem, ProxySettingsInput } from './proxySettingsApi';
export type { ReleaseCandidate, GrabResult, SearchParams } from './releaseApi';
export type { ImportList, ImportListExclusion, ProviderInfo, SyncResult, CreateImportListInput, UpdateImportListInput, CreateExclusionInput, TMDBPopularConfig, TMDBListConfig, ProviderType, } from './importListsApi';
export type { CategorySettingsItem, CategorySettingsInput } from './categorySettingsApi';
//# sourceMappingURL=index.d.ts.map