export const routeMap = {
    series: '/api/series',
    seriesDetail: (id) => `/api/series/${id}`,
    seriesMonitored: (id) => `/api/series/${id}/monitored`,
    seriesMonitoring: (id) => `/api/series/${id}/monitoring`,
    seriesBulkMonitoring: '/api/series/bulk/monitoring',
    seriesSeasonMonitoring: (seriesId, seasonNumber) => `/api/series/${seriesId}/seasons/${seasonNumber}/monitoring`,
    seriesDelete: (id) => `/api/series/${id}`,
    episodeMonitored: (id) => `/api/episodes/${id}`,
    filters: '/api/filters',
    filterDetail: (id) => `/api/filters/${id}`,
    filtersCustom: '/api/filters/custom',
    filterCustomDetail: (id) => `/api/filters/custom/${id}`,
    movies: '/api/movies',
    movieDetail: (id) => `/api/movies/${id}`,
    movieMonitored: (id) => `/api/movies/${id}/monitored`,
    movieDelete: (id) => `/api/movies/${id}`,
    moviesMissing: '/api/movies/missing',
    moviesCutoffUnmet: '/api/movies/cutoff-unmet',
    wanted: '/api/media/wanted',
    missingEpisodes: '/api/episodes/missing',
    cutoffUnmetEpisodes: '/api/episodes/cutoff-unmet',
    mediaSearch: '/api/media/search',
    mediaCreate: '/api/media',
    releaseSearch: '/api/releases/search',
    releaseGrab: '/api/releases/grab',
    torrents: '/api/torrents',
    torrentDetail: (infoHash) => `/api/torrents/${infoHash}`,
    torrentPause: (infoHash) => `/api/torrents/${infoHash}/pause`,
    torrentResume: (infoHash) => `/api/torrents/${infoHash}/resume`,
    torrentDelete: (infoHash) => `/api/torrents/${infoHash}`,
    torrentSpeedLimits: '/api/torrents/speed-limits',
    indexers: '/api/indexers',
    indexerSchema: (configContract, definitionId) => {
        const encodedContract = encodeURIComponent(configContract);
        if (!definitionId) {
            return `/api/indexers/schema/${encodedContract}`;
        }
        return `/api/indexers/schema/${encodedContract}?definitionId=${encodeURIComponent(definitionId)}`;
    },
    indexerUpdate: (id) => `/api/indexers/${id}`,
    indexerDelete: (id) => `/api/indexers/${id}`,
    indexerTest: (id) => `/api/indexers/${id}/test`,
    indexerClone: (id) => `/api/indexers/${id}/clone`,
    indexerTestDraft: '/api/indexers/test',
    appProfiles: '/api/profiles/app',
    appProfile: (id) => `/api/profiles/app/${id}`,
    appProfileClone: (id) => `/api/profiles/app/${id}/clone`,
    applications: '/api/applications',
    applicationUpdate: (id) => `/api/applications/${id}`,
    applicationDelete: (id) => `/api/applications/${id}`,
    applicationTest: (id) => `/api/applications/${id}/test`,
    applicationTestDraft: '/api/applications/test',
    applicationSync: (id) => `/api/applications/${id}/sync`,
    applicationSyncAll: '/api/applications/sync',
    subtitleMovieVariants: (id) => `/api/subtitles/movie/${id}/variants`,
    subtitleMovieSync: (id) => `/api/subtitles/movie/${id}/sync`,
    subtitleMovieScan: (id) => `/api/subtitles/movie/${id}/scan`,
    subtitleMovieSearch: (id) => `/api/subtitles/movie/${id}/search`,
    subtitleMoviesBulk: '/api/subtitles/movies/bulk',
    subtitleEpisodeVariants: (id) => `/api/subtitles/episode/${id}/variants`,
    subtitleSearch: '/api/subtitles/search',
    subtitleDownload: '/api/subtitles/download',
    subtitleUpload: '/api/subtitles/upload',
    subtitleHistory: '/api/subtitles/history',
    subtitleHistoryStats: '/api/subtitles/history/stats',
    subtitleSeriesVariants: (seriesId) => `/api/subtitles/series/${seriesId}/variants`,
    subtitleEpisodeSubtitles: (episodeId) => `/api/subtitles/episodes/${episodeId}`,
    subtitleSeriesSync: (seriesId) => `/api/subtitles/series/${seriesId}/sync`,
    subtitleSeriesScan: (seriesId) => `/api/subtitles/series/${seriesId}/scan`,
    subtitleSeriesSearch: (seriesId) => `/api/subtitles/series/${seriesId}/search`,
    subtitleProviders: '/api/subtitles/providers',
    subtitleProvider: (id) => `/api/subtitles/providers/${id}`,
    subtitleProviderTest: (id) => `/api/subtitles/providers/${id}/test`,
    subtitleProviderReset: (id) => `/api/subtitles/providers/${id}/reset`,
    subtitleBlacklistSeries: '/api/subtitles/blacklist/series',
    subtitleBlacklistMovies: '/api/subtitles/blacklist/movies',
    subtitleBlacklistItem: (id) => `/api/subtitles/blacklist/${id}`,
    subtitleBlacklistSeriesClear: '/api/subtitles/blacklist/series',
    subtitleBlacklistMoviesClear: '/api/subtitles/blacklist/movies',
    subtitleWantedSeries: '/api/subtitles/wanted/series',
    subtitleWantedMovies: '/api/subtitles/wanted/movies',
    subtitleWantedSeriesSearch: '/api/subtitles/wanted/series/search',
    subtitleWantedMoviesSearch: '/api/subtitles/wanted/movies/search',
    subtitleWantedSeriesItemSearch: (seriesId) => `/api/subtitles/wanted/series/${seriesId}/search`,
    subtitleWantedMovieItemSearch: (movieId) => `/api/subtitles/wanted/movies/${movieId}/search`,
    subtitleWantedCount: '/api/subtitles/wanted/count',
    activity: '/api/activity',
    activityClear: '/api/activity',
    activityMarkFailed: (id) => `/api/activity/${id}/fail`,
    activityExport: '/api/activity/export',
    blocklist: '/api/blocklist',
    blocklistRemove: '/api/blocklist/remove',
    blocklistClear: '/api/blocklist/clear',
    health: '/api/health',
    settings: '/api/settings',
    settingsProxies: '/api/settings/proxies',
    settingsProxy: (id) => `/api/settings/proxies/${id}`,
    settingsCategories: '/api/settings/categories',
    settingsCategory: (id) => `/api/settings/categories/${id}`,
    downloadClients: '/api/download-clients',
    downloadClientUpdate: (id) => `/api/download-clients/${id}`,
    downloadClientDelete: (id) => `/api/download-clients/${id}`,
    downloadClientTest: (id) => `/api/download-clients/${id}/test`,
    downloadClientTestDraft: '/api/download-clients/test',
    notifications: '/api/notifications',
    notificationUpdate: (id) => `/api/notifications/${id}`,
    notificationDelete: (id) => `/api/notifications/${id}`,
    notificationTest: (id) => `/api/notifications/${id}/test`,
    notificationTestDraft: '/api/notifications/test',
    tasksScheduled: '/api/tasks/scheduled',
    tasksQueued: '/api/tasks/queued',
    tasksHistory: '/api/tasks/history',
    taskDetails: (id) => `/api/tasks/history/${id}`,
    taskRun: (taskId) => `/api/tasks/scheduled/${taskId}/run`,
    taskCancel: (taskId) => `/api/tasks/queued/${taskId}`,
    systemEvents: '/api/system/events',
    systemEventsClear: '/api/system/events/clear',
    systemEventsExport: '/api/system/events/export',
    tags: '/api/tags',
    tagUpdate: (id) => `/api/tags/${id}`,
    tagDelete: (id) => `/api/tags/${id}`,
    tagDetails: (id) => `/api/tags/${id}/details`,
    tagAssignments: (id) => `/api/tags/${id}/assignments`,
    qualityProfiles: '/api/quality-profiles',
    qualityProfile: (id) => `/api/quality-profiles/${id}`,
    languageProfiles: '/api/subtitles/language-profiles',
    languageProfile: (id) => `/api/subtitles/language-profiles/${id}`,
    eventsStream: '/api/events/stream',
    backups: '/api/backups',
    backupCreate: '/api/backups',
    backupSchedule: '/api/backups/schedule',
    backupRestore: (id) => `/api/backups/${id}/restore`,
    backupDownload: (id) => `/api/backups/${id}/download`,
    backupDelete: (id) => `/api/backups/${id}`,
    logsFiles: '/api/logs/files',
    logsFile: (filename) => `/api/logs/files/${encodeURIComponent(filename)}`,
    logsFileDownload: (filename) => `/api/logs/files/${encodeURIComponent(filename)}/download`,
    logsFileClear: (filename) => `/api/logs/files/${encodeURIComponent(filename)}/clear`,
    updatesCurrent: '/api/updates/current',
    updatesAvailable: '/api/updates/available',
    updatesCheck: '/api/updates/check',
    updatesInstall: '/api/updates/install',
    updatesHistory: '/api/updates/history',
    updatesProgress: (updateId) => `/api/updates/progress/${updateId}`,
    collections: '/api/collections',
    collectionDetail: (id) => `/api/collections/${id}`,
    collectionUpdate: (id) => `/api/collections/${id}`,
    collectionDelete: (id) => `/api/collections/${id}`,
    collectionSearch: (id) => `/api/collections/${id}/search`,
    collectionSync: (id) => `/api/collections/${id}/sync`,
    discover: '/api/discover/movies',
    importScan: '/api/import/scan',
    importSeries: '/api/import/series',
    importBulkSeries: '/api/import/series/bulk',
    customFormats: '/api/custom-formats',
    customFormat: (id) => `/api/custom-formats/${id}`,
    customFormatTest: (id) => `/api/custom-formats/${id}/test`,
    customFormatSchema: '/api/custom-formats/schema',
};
//# sourceMappingURL=routeMap.js.map