export declare const routeMap: {
    series: string;
    seriesDetail: (id: number) => string;
    seriesMonitored: (id: number) => string;
    seriesMonitoring: (id: number) => string;
    seriesBulkMonitoring: string;
    seriesSeasonMonitoring: (seriesId: number, seasonNumber: number) => string;
    seriesDelete: (id: number) => string;
    episodeMonitored: (id: number) => string;
    filters: string;
    filterDetail: (id: number) => string;
    filtersCustom: string;
    filterCustomDetail: (id: number) => string;
    movies: string;
    movieDetail: (id: number) => string;
    movieMonitored: (id: number) => string;
    movieDelete: (id: number) => string;
    moviesMissing: string;
    moviesCutoffUnmet: string;
    wanted: string;
    missingEpisodes: string;
    cutoffUnmetEpisodes: string;
    mediaSearch: string;
    mediaCreate: string;
    releaseSearch: string;
    releaseGrab: string;
    torrents: string;
    torrentDetail: (infoHash: string) => string;
    torrentPause: (infoHash: string) => string;
    torrentResume: (infoHash: string) => string;
    torrentDelete: (infoHash: string) => string;
    torrentSpeedLimits: string;
    indexers: string;
    indexerSchema: (configContract: string, definitionId?: string) => string;
    indexerUpdate: (id: number) => string;
    indexerDelete: (id: number) => string;
    indexerTest: (id: number) => string;
    indexerClone: (id: number) => string;
    indexerTestDraft: string;
    appProfiles: string;
    appProfile: (id: number) => string;
    appProfileClone: (id: number) => string;
    applications: string;
    applicationUpdate: (id: number) => string;
    applicationDelete: (id: number) => string;
    applicationTest: (id: number) => string;
    applicationTestDraft: string;
    applicationSync: (id: number) => string;
    applicationSyncAll: string;
    subtitleMovieVariants: (id: number) => string;
    subtitleMovieSync: (id: number) => string;
    subtitleMovieScan: (id: number) => string;
    subtitleMovieSearch: (id: number) => string;
    subtitleMoviesBulk: string;
    subtitleEpisodeVariants: (id: number) => string;
    subtitleSearch: string;
    subtitleDownload: string;
    subtitleUpload: string;
    subtitleHistory: string;
    subtitleHistoryStats: string;
    subtitleSeriesVariants: (seriesId: number) => string;
    subtitleEpisodeSubtitles: (episodeId: number) => string;
    subtitleSeriesSync: (seriesId: number) => string;
    subtitleSeriesScan: (seriesId: number) => string;
    subtitleSeriesSearch: (seriesId: number) => string;
    subtitleProviders: string;
    subtitleProvider: (id: string) => string;
    subtitleProviderTest: (id: string) => string;
    subtitleProviderReset: (id: string) => string;
    subtitleBlacklistSeries: string;
    subtitleBlacklistMovies: string;
    subtitleBlacklistItem: (id: number) => string;
    subtitleBlacklistSeriesClear: string;
    subtitleBlacklistMoviesClear: string;
    subtitleWantedSeries: string;
    subtitleWantedMovies: string;
    subtitleWantedSeriesSearch: string;
    subtitleWantedMoviesSearch: string;
    subtitleWantedSeriesItemSearch: (seriesId: number) => string;
    subtitleWantedMovieItemSearch: (movieId: number) => string;
    subtitleWantedCount: string;
    activity: string;
    activityClear: string;
    activityMarkFailed: (id: number) => string;
    activityExport: string;
    blocklist: string;
    blocklistRemove: string;
    blocklistClear: string;
    health: string;
    settings: string;
    settingsProxies: string;
    settingsProxy: (id: number) => string;
    settingsCategories: string;
    settingsCategory: (id: number) => string;
    downloadClients: string;
    downloadClientUpdate: (id: number) => string;
    downloadClientDelete: (id: number) => string;
    downloadClientTest: (id: number) => string;
    downloadClientTestDraft: string;
    notifications: string;
    notificationUpdate: (id: number) => string;
    notificationDelete: (id: number) => string;
    notificationTest: (id: number) => string;
    notificationTestDraft: string;
    tasksScheduled: string;
    tasksQueued: string;
    tasksHistory: string;
    taskDetails: (id: number) => string;
    taskRun: (taskId: string | number) => string;
    taskCancel: (taskId: number) => string;
    systemEvents: string;
    systemEventsClear: string;
    systemEventsExport: string;
    tags: string;
    tagUpdate: (id: number) => string;
    tagDelete: (id: number) => string;
    tagDetails: (id: number) => string;
    tagAssignments: (id: number) => string;
    qualityProfiles: string;
    qualityProfile: (id: number) => string;
    languageProfiles: string;
    languageProfile: (id: number) => string;
    eventsStream: string;
    backups: string;
    backupCreate: string;
    backupSchedule: string;
    backupRestore: (id: number) => string;
    backupDownload: (id: number) => string;
    backupDelete: (id: number) => string;
    logsFiles: string;
    logsFile: (filename: string) => string;
    logsFileDownload: (filename: string) => string;
    logsFileClear: (filename: string) => string;
    updatesCurrent: string;
    updatesAvailable: string;
    updatesCheck: string;
    updatesInstall: string;
    updatesHistory: string;
    updatesProgress: (updateId: string) => string;
    collections: string;
    collectionDetail: (id: number) => string;
    collectionUpdate: (id: number) => string;
    collectionDelete: (id: number) => string;
    collectionSearch: (id: number) => string;
    collectionSync: (id: number) => string;
    discover: string;
    importScan: string;
    importSeries: string;
    importBulkSeries: string;
    customFormats: string;
    customFormat: (id: number) => string;
    customFormatTest: (id: number) => string;
    customFormatSchema: string;
};
//# sourceMappingURL=routeMap.d.ts.map