import { z } from 'zod';
import { ApiHttpClient, type PaginatedResult } from './httpClient';
import type { CutoffUnmetMoviesQuery, MissingMoviesQuery } from '../../types/wanted';
declare const missingMovieSchema: z.ZodObject<{
    id: z.ZodNumber;
    movieId: z.ZodNumber;
    title: z.ZodString;
    year: z.ZodNumber;
    posterUrl: z.ZodOptional<z.ZodString>;
    status: z.ZodEnum<["missing", "announced", "incinemas", "released"]>;
    monitored: z.ZodBoolean;
    cinemaDate: z.ZodOptional<z.ZodString>;
    physicalRelease: z.ZodOptional<z.ZodString>;
    digitalRelease: z.ZodOptional<z.ZodString>;
    qualityProfileId: z.ZodNumber;
    qualityProfileName: z.ZodOptional<z.ZodString>;
    runtime: z.ZodOptional<z.ZodNumber>;
    certification: z.ZodOptional<z.ZodString>;
    genres: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    status: "released" | "missing" | "announced" | "incinemas";
    title: string;
    qualityProfileId: number;
    id: number;
    monitored: boolean;
    year: number;
    movieId: number;
    posterUrl?: string | undefined;
    genres?: string[] | undefined;
    certification?: string | undefined;
    runtime?: number | undefined;
    qualityProfileName?: string | undefined;
    cinemaDate?: string | undefined;
    physicalRelease?: string | undefined;
    digitalRelease?: string | undefined;
}, {
    status: "released" | "missing" | "announced" | "incinemas";
    title: string;
    qualityProfileId: number;
    id: number;
    monitored: boolean;
    year: number;
    movieId: number;
    posterUrl?: string | undefined;
    genres?: string[] | undefined;
    certification?: string | undefined;
    runtime?: number | undefined;
    qualityProfileName?: string | undefined;
    cinemaDate?: string | undefined;
    physicalRelease?: string | undefined;
    digitalRelease?: string | undefined;
}>;
declare const cutoffUnmetMovieSchema: z.ZodObject<{
    id: z.ZodNumber;
    movieId: z.ZodNumber;
    title: z.ZodString;
    year: z.ZodNumber;
    posterUrl: z.ZodOptional<z.ZodString>;
    monitored: z.ZodBoolean;
    currentQuality: z.ZodString;
    cutoffQuality: z.ZodString;
    qualityProfileId: z.ZodNumber;
    qualityProfileName: z.ZodOptional<z.ZodString>;
    fileId: z.ZodNumber;
    filePath: z.ZodString;
    fileSize: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    title: string;
    qualityProfileId: number;
    id: number;
    monitored: boolean;
    year: number;
    movieId: number;
    currentQuality: string;
    cutoffQuality: string;
    filePath: string;
    fileId: number;
    fileSize: number;
    posterUrl?: string | undefined;
    qualityProfileName?: string | undefined;
}, {
    title: string;
    qualityProfileId: number;
    id: number;
    monitored: boolean;
    year: number;
    movieId: number;
    currentQuality: string;
    cutoffQuality: string;
    filePath: string;
    fileId: number;
    fileSize: number;
    posterUrl?: string | undefined;
    qualityProfileName?: string | undefined;
}>;
export type MissingMovie = z.infer<typeof missingMovieSchema>;
export type CutoffUnmetMovie = z.infer<typeof cutoffUnmetMovieSchema>;
export declare function createWantedApi(client: ApiHttpClient): {
    listMissingMovies(query?: MissingMoviesQuery): Promise<PaginatedResult<MissingMovie>>;
    listCutoffUnmetMovies(query?: CutoffUnmetMoviesQuery): Promise<PaginatedResult<CutoffUnmetMovie>>;
};
export {};
//# sourceMappingURL=wantedApi.d.ts.map