'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon } from '@/components/primitives/Icon';
import { ProgressBar } from '@/components/primitives/ProgressBar';
export function CollectionCard({ collection, onToggleMonitored, onSearch, onEdit, onDelete, }) {
    const progress = collection.movieCount > 0
        ? (collection.moviesInLibrary / collection.movieCount) * 100
        : 0;
    const posterUrl = collection.posterUrl ?? '/images/placeholder-poster.png';
    return (_jsxs("article", { className: "group flex flex-col gap-3 overflow-hidden rounded-md border border-border-subtle bg-surface-1 transition-all hover:shadow-elevation-2", children: [_jsxs("div", { className: "relative aspect-[2/3] overflow-hidden bg-surface-2", children: [_jsx("img", { src: posterUrl, alt: collection.name, className: "h-full w-full object-cover transition-transform duration-300 group-hover:scale-105", loading: "lazy", onError: event => {
                            const target = event.currentTarget;
                            target.src = '/images/placeholder-poster.png';
                        } }), _jsx("button", { type: "button", onClick: () => onToggleMonitored(collection.id, !collection.monitored), className: "absolute left-2 top-2 flex items-center justify-center rounded-full p-1.5 transition-colors hover:bg-surface-2/80", "aria-label": collection.monitored ? 'Disable monitoring' : 'Enable monitoring', children: collection.monitored ? (_jsx(Icon, { name: "success", className: "text-status-completed" })) : (_jsx(Icon, { name: "warning", className: "text-text-muted" })) }), _jsxs("div", { className: "absolute right-2 top-2 flex items-center gap-1 rounded-full bg-surface-0/90 px-2 py-1 text-xs font-medium text-text-primary", children: [_jsx(Icon, { name: "grid", className: "h-3 w-3" }), _jsxs("span", { children: [collection.moviesInLibrary, "/", collection.movieCount] })] }), _jsxs("div", { className: "absolute inset-0 flex items-center justify-center gap-2 bg-surface-0/80 opacity-0 transition-opacity group-hover:opacity-100", children: [_jsx("button", { type: "button", onClick: () => onSearch(collection.id), className: "rounded-md bg-surface-2 p-2 transition-colors hover:bg-surface-3", "aria-label": `Search ${collection.name}`, children: _jsx(Icon, { name: "search" }) }), _jsx("button", { type: "button", onClick: () => onEdit(collection), className: "rounded-md bg-surface-2 p-2 transition-colors hover:bg-surface-3", "aria-label": `Edit ${collection.name}`, children: _jsx(Icon, { name: "edit" }) }), _jsx("button", { type: "button", onClick: () => onDelete(collection.id), className: "rounded-md bg-status-error/20 p-2 text-status-error transition-colors hover:bg-status-error/30", "aria-label": `Delete ${collection.name}`, children: _jsx(Icon, { name: "trash" }) })] })] }), _jsxs("div", { className: "flex flex-1 flex-col gap-2 px-3 pb-3", children: [_jsx("h3", { className: "line-clamp-2 text-sm font-semibold text-text-primary group-hover:text-accent-primary", children: collection.name }), collection.overview && (_jsx("p", { className: "line-clamp-3 text-xs text-text-secondary", children: collection.overview })), _jsx("div", { className: "mt-auto", children: _jsx(ProgressBar, { value: progress, label: `${collection.moviesInLibrary} of ${collection.movieCount} movies in library` }) })] })] }));
}
//# sourceMappingURL=CollectionCard.js.map