export const PROWLARR_ROUTE_PATHS = [
  '/indexers',
  '/indexers/stats',
  '/search',
  '/history',
  '/settings/indexers',
  '/settings/applications',
  '/settings/downloadclients',
  '/settings/connect',
  '/settings/tags',
  '/settings/general',
  '/settings/ui',
  '/system/status',
  '/system/tasks',
  '/system/backup',
  '/system/updates',
  '/system/events',
  '/system/logs/files',
] as const;
