import type { ListQuery, WantedQuery } from '../api/mediaApi';
import type { ActivityQuery } from '../api/activityApi';
import type { CalendarListParams } from '../../types/calendar';
import type { BlocklistQuery } from '../../types/blocklist';
import type { EventsQuery, TaskHistoryQuery } from '../api/systemApi';
import type { UpdateHistoryQuery } from '../api/updatesApi';
import type { TorrentListQuery } from '../api/torrentApi';
import type { MissingEpisodesQuery, CutoffUnmetEpisodesQuery, MissingMoviesQuery, CutoffUnmetMoviesQuery } from '../../types/wanted';
import type { WantedQueryParams } from '../api/subtitleWantedApi';
import type { HistoryQueryParams, StatsQueryParams } from '../api/subtitleHistoryApi';
import type { BlacklistQueryParams } from '../api/subtitleBlacklistApi';
export declare const queryKeys: {
    seriesList: (query: ListQuery) => readonly ["series", "list", ListQuery];
    seriesDetail: (id: number) => readonly ["series", "detail", number];
    filtersList: (type: "series" | "indexer") => readonly ["filters", "series" | "indexer"];
    moviesList: (query: ListQuery) => readonly ["movies", "list", ListQuery];
    movieDetail: (id: number) => readonly ["movies", "detail", number];
    wantedList: (query: WantedQuery) => readonly ["media", "wanted", WantedQuery];
    missingEpisodes: (query: MissingEpisodesQuery) => readonly ["episodes", "missing", MissingEpisodesQuery];
    cutoffUnmetEpisodes: (query: CutoffUnmetEpisodesQuery) => readonly ["episodes", "cutoff-unmet", CutoffUnmetEpisodesQuery];
    missingMovies: (query: MissingMoviesQuery) => readonly ["movies", "missing", MissingMoviesQuery];
    cutoffUnmetMovies: (query: CutoffUnmetMoviesQuery) => readonly ["movies", "cutoff-unmet", CutoffUnmetMoviesQuery];
    releaseCandidates: (request: Record<string, unknown>) => readonly ["media", "release-candidates", Record<string, unknown>];
    calendar: (params: CalendarListParams) => readonly ["calendar", "list", CalendarListParams];
    collections: () => readonly ["collections", "list"];
    collectionDetail: (id: number) => readonly ["collections", "detail", number];
    discoverMovies: (mode: string) => readonly ["discover", "movies", string];
    indexers: () => readonly ["indexers", "list"];
    appProfiles: () => readonly ["app-profiles", "list"];
    applications: () => readonly ["applications", "list"];
    torrents: (query: TorrentListQuery) => readonly ["torrents", "list", TorrentListQuery];
    activity: (query: ActivityQuery) => readonly ["activity", "list", ActivityQuery];
    blocklist: (query: BlocklistQuery) => readonly ["blocklist", "list", BlocklistQuery];
    downloadClients: () => readonly ["download-clients", "list"];
    notifications: () => readonly ["notifications", "list"];
    tags: () => readonly ["tags", "list"];
    tagDetails: (id: number) => readonly ["tags", "details", number];
    qualityProfiles: () => readonly ["quality-profiles", "list"];
    qualityProfile: (id: number) => readonly ["quality-profiles", "detail", number];
    customFormats: () => readonly ["custom-formats", "list"];
    customFormat: (id: number) => readonly ["custom-formats", "detail", number];
    customFormatSchema: () => readonly ["custom-formats", "schema"];
    languageProfiles: () => readonly ["language-profiles", "list"];
    health: () => readonly ["health"];
    settings: () => readonly ["settings"];
    settingsProxies: () => readonly ["settings", "proxies"];
    settingsCategories: () => readonly ["settings", "categories"];
    systemStatus: () => readonly ["system", "status"];
    systemEvents: (query: EventsQuery) => readonly ["system", "events", EventsQuery];
    tasksScheduled: () => readonly ["tasks", "scheduled"];
    tasksQueued: () => readonly ["tasks", "queued"];
    tasksHistory: (query: TaskHistoryQuery) => readonly ["tasks", "history", TaskHistoryQuery];
    taskDetails: (id: number) => readonly ["tasks", "details", number];
    backups: () => readonly ["backups", "list"];
    backupSchedule: () => readonly ["backups", "schedule"];
    logsFiles: () => readonly ["logs", "files"];
    logsFileContents: (filename: string, query?: {
        limit?: number;
    }) => readonly ["logs", "file", string, {
        limit?: number;
    } | undefined];
    updatesCurrent: () => readonly ["updates", "current"];
    updatesAvailable: () => readonly ["updates", "available"];
    updatesHistory: (query: UpdateHistoryQuery) => readonly ["updates", "history", UpdateHistoryQuery];
    updatesProgress: (updateId: string) => readonly ["updates", "progress", string];
    subtitleWantedCount: () => readonly ["subtitle-wanted", "count"];
    subtitleWantedSeries: (query: WantedQueryParams) => readonly ["subtitle-wanted", "series", WantedQueryParams];
    subtitleWantedMovies: (query: WantedQueryParams) => readonly ["subtitle-wanted", "movies", WantedQueryParams];
    subtitleHistory: (type: "series" | "movies", params: HistoryQueryParams) => readonly ["subtitle-history", "series" | "movies", HistoryQueryParams];
    subtitleHistoryStats: (params: StatsQueryParams) => readonly ["subtitle-history-stats", StatsQueryParams];
    subtitleBlacklistSeries: (params: BlacklistQueryParams) => readonly ["subtitle-blacklist", "series", BlacklistQueryParams];
    subtitleBlacklistMovies: (params: BlacklistQueryParams) => readonly ["subtitle-blacklist", "movies", BlacklistQueryParams];
    subtitleProviders: () => readonly ["subtitle-providers"];
    subtitleProvider: (id: string) => readonly ["subtitle-provider", string];
    importLists: () => readonly ["import-lists"];
    importList: (id: number) => readonly ["import-lists", "detail", number];
    importListProviders: () => readonly ["import-lists", "providers"];
    importListExclusions: () => readonly ["import-lists", "exclusions"];
};
export type QueryKeyFactory = typeof queryKeys;
//# sourceMappingURL=queryKeys.d.ts.map