export interface ApiRouteDefinition {
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
}

export const API_ROUTE_MAP: ApiRouteDefinition[] = [
  { method: 'GET', path: '/api/calendar' },

  { method: 'GET', path: '/api/series' },
  { method: 'GET', path: '/api/series/:id' },
  { method: 'POST', path: '/api/series/:id/search' },
  { method: 'PATCH', path: '/api/series/:id/monitored' },
  { method: 'PUT', path: '/api/series/:id/monitoring' },
  { method: 'PUT', path: '/api/series/bulk' },
  { method: 'PUT', path: '/api/series/bulk/monitoring' },
  { method: 'GET', path: '/api/movies/root-folders' },
  { method: 'PATCH', path: '/api/series/:seriesId/seasons/:seasonNumber/monitoring' },
  { method: 'PATCH', path: '/api/episodes/:id' },
  { method: 'DELETE', path: '/api/series/:id' },

  { method: 'GET', path: '/api/filters' },
  { method: 'POST', path: '/api/filters' },
  { method: 'PUT', path: '/api/filters/:id' },
  { method: 'DELETE', path: '/api/filters/:id' },
  { method: 'GET', path: '/api/filters/custom' },
  { method: 'POST', path: '/api/filters/custom' },
  { method: 'PUT', path: '/api/filters/custom/:id' },
  { method: 'DELETE', path: '/api/filters/custom/:id' },

  { method: 'GET', path: '/api/movies' },
  { method: 'GET', path: '/api/movies/:id' },
  { method: 'POST', path: '/api/movies/:id/search' },
  { method: 'PATCH', path: '/api/movies/:id/monitored' },
  { method: 'DELETE', path: '/api/movies/:id' },

  { method: 'GET', path: '/api/media/wanted' },
  { method: 'POST', path: '/api/media/search' },
  { method: 'POST', path: '/api/media' },

  { method: 'GET', path: '/api/stream/:id' },
  { method: 'GET', path: '/api/playback/:id' },
  { method: 'GET', path: '/api/playback/continue-watching' },
  { method: 'POST', path: '/api/playback/progress' },
  { method: 'GET', path: '/api/playback/subtitles/:trackId' },

  { method: 'POST', path: '/api/releases/search' },
  { method: 'POST', path: '/api/releases/grab' },
  { method: 'POST', path: '/api/releases/grab-candidate' },

  { method: 'GET', path: '/api/torrents' },
  { method: 'GET', path: '/api/torrents/:infoHash' },
  { method: 'POST', path: '/api/torrents' },
  { method: 'PATCH', path: '/api/torrents/:infoHash/pause' },
  { method: 'PATCH', path: '/api/torrents/:infoHash/resume' },
  { method: 'DELETE', path: '/api/torrents/:infoHash' },
  { method: 'POST', path: '/api/torrents/:infoHash/retry-import' },
  { method: 'PATCH', path: '/api/torrents/speed-limits' },

  { method: 'GET', path: '/api/indexers' },
  { method: 'GET', path: '/api/indexers/schema/:configContract' },
  { method: 'POST', path: '/api/indexers' },
  { method: 'POST', path: '/api/indexers/test' },
  { method: 'PUT', path: '/api/indexers/:id' },
  { method: 'DELETE', path: '/api/indexers/:id' },
  { method: 'POST', path: '/api/indexers/:id/test' },
  { method: 'POST', path: '/api/indexers/:id/clone' },

  { method: 'GET', path: '/api/subtitles/movie/:id/variants' },
  { method: 'POST', path: '/api/subtitles/movie/:id/sync' },
  { method: 'POST', path: '/api/subtitles/movie/:id/scan' },
  { method: 'POST', path: '/api/subtitles/movie/:id/search' },
  { method: 'PUT', path: '/api/subtitles/movies/bulk' },
  { method: 'GET', path: '/api/subtitles/episode/:id/variants' },
  { method: 'GET', path: '/api/subtitles/episodes/:id' },
  { method: 'GET', path: '/api/subtitles/series/:id/variants' },
  { method: 'POST', path: '/api/subtitles/series/:id/sync' },
  { method: 'POST', path: '/api/subtitles/series/:id/scan' },
  { method: 'POST', path: '/api/subtitles/series/:id/search' },
  { method: 'POST', path: '/api/subtitles/search' },
  { method: 'POST', path: '/api/subtitles/download' },
  { method: 'POST', path: '/api/subtitles/upload' },
  { method: 'GET', path: '/api/subtitles/providers' },
  { method: 'GET', path: '/api/subtitles/providers/:id' },
  { method: 'PUT', path: '/api/subtitles/providers/:id' },
  { method: 'POST', path: '/api/subtitles/providers/:id/test' },
  { method: 'POST', path: '/api/subtitles/providers/:id/reset' },
  { method: 'GET', path: '/api/subtitles/wanted/series' },
  { method: 'GET', path: '/api/subtitles/wanted/movies' },
  { method: 'GET', path: '/api/subtitles/wanted/count' },
  { method: 'POST', path: '/api/subtitles/wanted/series/search' },
  { method: 'POST', path: '/api/subtitles/wanted/movies/search' },
  { method: 'POST', path: '/api/subtitles/wanted/series/:id/search' },
  { method: 'POST', path: '/api/subtitles/wanted/movies/:id/search' },
  { method: 'GET', path: '/api/subtitles/history' },
  { method: 'DELETE', path: '/api/subtitles/history' },
  { method: 'GET', path: '/api/subtitles/history/stats' },
  { method: 'GET', path: '/api/subtitles/blacklist/series' },
  { method: 'DELETE', path: '/api/subtitles/blacklist/series' },
  { method: 'GET', path: '/api/subtitles/blacklist/movies' },
  { method: 'DELETE', path: '/api/subtitles/blacklist/movies' },
  { method: 'DELETE', path: '/api/subtitles/blacklist/:id' },

  { method: 'GET', path: '/api/activity' },
  { method: 'DELETE', path: '/api/activity' },
  { method: 'PATCH', path: '/api/activity/:id/fail' },
  { method: 'POST', path: '/api/activity/:id/retry-import' },
  { method: 'GET', path: '/api/activity/export' },
  { method: 'GET', path: '/api/health' },
  { method: 'GET', path: '/api/settings' },
  { method: 'PATCH', path: '/api/settings' },
  { method: 'GET', path: '/api/settings/proxies' },
  { method: 'POST', path: '/api/settings/proxies' },
  { method: 'PUT', path: '/api/settings/proxies/:id' },
  { method: 'DELETE', path: '/api/settings/proxies/:id' },
  { method: 'GET', path: '/api/settings/categories' },
  { method: 'POST', path: '/api/settings/categories' },
  { method: 'PUT', path: '/api/settings/categories/:id' },
  { method: 'DELETE', path: '/api/settings/categories/:id' },

  { method: 'GET', path: '/api/events/stream' },

  // System routes
  { method: 'GET', path: '/api/system/status' },
  { method: 'GET', path: '/api/tasks/scheduled' },
  { method: 'GET', path: '/api/tasks/queued' },
  { method: 'GET', path: '/api/tasks/history' },
  { method: 'GET', path: '/api/tasks/history/:id' },
  { method: 'POST', path: '/api/tasks/scheduled/:taskId/run' },
  { method: 'DELETE', path: '/api/tasks/queued/:taskId' },
  { method: 'GET', path: '/api/system/events' },
  { method: 'DELETE', path: '/api/system/events/clear' },
  { method: 'GET', path: '/api/system/events/export' },

  // Backup routes
  { method: 'GET', path: '/api/backups' },
  { method: 'POST', path: '/api/backups' },
  { method: 'GET', path: '/api/backups/schedule' },
  { method: 'PATCH', path: '/api/backups/schedule' },
  { method: 'POST', path: '/api/backups/:id/restore' },
  { method: 'POST', path: '/api/backups/:id/download' },
  { method: 'GET', path: '/api/backups/:id/file' },
  { method: 'DELETE', path: '/api/backups/:id' },

  // Logs routes
  { method: 'GET', path: '/api/logs/files' },
  { method: 'GET', path: '/api/logs/files/:filename' },
  { method: 'DELETE', path: '/api/logs/files/:filename' },
  { method: 'POST', path: '/api/logs/files/:filename/clear' },
  { method: 'GET', path: '/api/logs/files/:filename/download' },
  { method: 'GET', path: '/api/logs/files/:filename/raw' },

  // Updates routes
  { method: 'GET', path: '/api/updates/current' },
  { method: 'GET', path: '/api/updates/available' },
  { method: 'GET', path: '/api/updates/check' },
  { method: 'POST', path: '/api/updates/check' },
  { method: 'POST', path: '/api/updates/download' },
  { method: 'POST', path: '/api/updates/install' },
  { method: 'GET', path: '/api/updates/history' },
  { method: 'GET', path: '/api/updates/progress/:updateId' },

  // Setup wizard routes
  { method: 'GET', path: '/api/setup/status' },
  { method: 'POST', path: '/api/setup/complete' },

  // Notification routes
  { method: 'GET', path: '/api/notifications' },
  { method: 'POST', path: '/api/notifications' },
  { method: 'POST', path: '/api/notifications/test' },
  { method: 'PUT', path: '/api/notifications/:id' },
  { method: 'DELETE', path: '/api/notifications/:id' },
  { method: 'POST', path: '/api/notifications/:id/test' },
  { method: 'GET', path: '/api/notifications/push-status' },

  // Download Client routes (speed-limits settings only; full CRUD deferred)
  { method: 'GET', path: '/api/download-client' },
  { method: 'PUT', path: '/api/download-client' },

  // Blocklist routes
  { method: 'GET', path: '/api/blocklist' },
  { method: 'DELETE', path: '/api/blocklist/remove' },
  { method: 'DELETE', path: '/api/blocklist/clear' },
  { method: 'DELETE', path: '/api/blocklist/:id' },

  // Quality Profile routes
  { method: 'GET', path: '/api/quality-profiles' },
  { method: 'GET', path: '/api/quality-profiles/:id' },
  { method: 'POST', path: '/api/quality-profiles' },
  { method: 'PUT', path: '/api/quality-profiles/:id' },
  { method: 'DELETE', path: '/api/quality-profiles/:id' },
  { method: 'GET', path: '/api/quality-definitions' },

  // Image proxy
  { method: 'GET', path: '/api/images/proxy' },
  // Production routes discovered by runtime Fastify registration. Keep this
  // list complete in both directions via tests/api-route-map.test.ts.
  { method: 'DELETE', path: '/api/collections/:id' },
  { method: 'DELETE', path: '/api/custom-formats/:id' },
  { method: 'DELETE', path: '/api/import-lists/:id' },
  { method: 'DELETE', path: '/api/import-lists/exclusions/:id' },
  { method: 'DELETE', path: '/api/subtitles/:id' },

  { method: 'GET', path: '/api/collections' },
  { method: 'GET', path: '/api/collections/:id' },
  { method: 'GET', path: '/api/custom-formats' },
  { method: 'GET', path: '/api/custom-formats/:id' },
  { method: 'GET', path: '/api/custom-formats/schema' },
  { method: 'GET', path: '/api/dashboard/disk-space' },
  { method: 'GET', path: '/api/dashboard/upcoming' },
  { method: 'GET', path: '/api/episodes/missing' },
  { method: 'GET', path: '/api/filesystem' },
  { method: 'GET', path: '/api/import-lists' },
  { method: 'GET', path: '/api/import-lists/:id' },
  { method: 'GET', path: '/api/import-lists/exclusions' },
  { method: 'GET', path: '/api/import-lists/providers' },
  { method: 'GET', path: '/api/indexers/:id/health' },
  { method: 'GET', path: '/api/indexers/catalog' },
  { method: 'GET', path: '/api/indexers/detect' },
  { method: 'GET', path: '/api/media/library' },
  { method: 'GET', path: '/api/movies/:id/tmdb-collection' },
  { method: 'GET', path: '/api/movies/missing' },
  { method: 'GET', path: '/api/scheduler/history' },
  { method: 'GET', path: '/api/scheduler/tasks' },
  { method: 'GET', path: '/api/search' },
  { method: 'GET', path: '/api/settings/media' },
  { method: 'GET', path: '/api/stats/downloads' },
  { method: 'GET', path: '/api/stats/system' },
  { method: 'GET', path: '/api/system/stats' },

  { method: 'PATCH', path: '/api/torrents/:infoHash/priority' },

  { method: 'POST', path: '/api/collections' },
  { method: 'POST', path: '/api/collections/:id/search' },
  { method: 'POST', path: '/api/collections/:id/sync' },
  { method: 'POST', path: '/api/custom-formats' },
  { method: 'POST', path: '/api/custom-formats/:id/test' },
  { method: 'POST', path: '/api/import-lists' },
  { method: 'POST', path: '/api/import-lists/:id/sync' },
  { method: 'POST', path: '/api/import-lists/exclusions' },
  { method: 'POST', path: '/api/import/backfill-posters' },
  { method: 'POST', path: '/api/import/execute' },
  { method: 'POST', path: '/api/import/scan' },
  { method: 'POST', path: '/api/import/search' },
  { method: 'POST', path: '/api/indexers/catalog/:id/add' },
  { method: 'POST', path: '/api/indexers/catalog/reload' },
  { method: 'POST', path: '/api/indexers/import-from/:type' },
  { method: 'POST', path: '/api/library/scan' },
  { method: 'POST', path: '/api/media/:id/auto-search' },
  { method: 'POST', path: '/api/movies/import/apply' },
  { method: 'POST', path: '/api/movies/import/scan' },
  { method: 'POST', path: '/api/movies/organize/preview' },
  { method: 'POST', path: '/api/scheduler/:taskId/trigger' },
  { method: 'POST', path: '/api/series/:id/rescan' },
  { method: 'POST', path: '/api/series/import/apply' },
  { method: 'POST', path: '/api/series/import/scan' },
  { method: 'POST', path: '/api/series/organize/preview' },
  { method: 'POST', path: '/api/subtitles/series/:id/season/:season/search' },
  { method: 'POST', path: '/api/torrents/bulk' },
  { method: 'POST', path: '/api/wanted' },
  { method: 'POST', path: '/api/wanted/search-all' },

  { method: 'PUT', path: '/api/collections/:id' },
  { method: 'PUT', path: '/api/custom-formats/:id' },
  { method: 'PUT', path: '/api/import-lists/:id' },
  { method: 'PUT', path: '/api/movies/:id' },
  { method: 'PUT', path: '/api/movies/bulk' },
  { method: 'PUT', path: '/api/movies/organize/apply' },
  { method: 'PUT', path: '/api/scheduler/:taskId/interval' },
  { method: 'PUT', path: '/api/scheduler/:taskId/toggle' },
  { method: 'PUT', path: '/api/series/organize/apply' },
  { method: 'PUT', path: '/api/settings/media' },

];
