'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { getLanguageName } from '@/lib/constants/languages';
import { Trash2 } from 'lucide-react';
export function LanguageSettingRow({ setting, onChange, onRemove, disabled = false, }) {
    const handleChange = (key, value) => {
        onChange({ ...setting, [key]: value });
    };
    return (_jsxs("div", { className: "flex items-center gap-3 rounded-md border border-border-subtle bg-surface-1 p-3", children: [_jsxs("div", { className: "flex-1 min-w-[150px]", children: [_jsx("span", { className: "text-sm font-medium text-text-primary", children: getLanguageName(setting.languageCode) }), _jsxs("span", { className: "ml-2 text-xs text-text-muted", children: ["(", setting.languageCode, ")"] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("label", { className: "flex items-center gap-1.5 text-xs text-text-secondary", children: [_jsx("input", { type: "checkbox", checked: setting.isForced, onChange: e => handleChange('isForced', e.target.checked), disabled: disabled, className: "h-4 w-4 rounded border-border-subtle bg-surface-2 text-accent-primary focus:ring-2 focus:ring-accent-primary/50 disabled:cursor-not-allowed disabled:opacity-50" }), "Forced"] }), _jsxs("label", { className: "flex items-center gap-1.5 text-xs text-text-secondary", children: [_jsx("input", { type: "checkbox", checked: setting.isHi, onChange: e => handleChange('isHi', e.target.checked), disabled: disabled, className: "h-4 w-4 rounded border-border-subtle bg-surface-2 text-accent-primary focus:ring-2 focus:ring-accent-primary/50 disabled:cursor-not-allowed disabled:opacity-50" }), "HI"] }), _jsxs("label", { className: "flex items-center gap-1.5 text-xs text-text-secondary", children: [_jsx("input", { type: "checkbox", checked: setting.audioExclude, onChange: e => handleChange('audioExclude', e.target.checked), disabled: disabled, className: "h-4 w-4 rounded border-border-subtle bg-surface-2 text-accent-primary focus:ring-2 focus:ring-accent-primary/50 disabled:cursor-not-allowed disabled:opacity-50" }), "Audio Exclude"] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("label", { htmlFor: `score-${setting.languageCode}`, className: "text-xs text-text-secondary", children: "Score:" }), _jsx("input", { id: `score-${setting.languageCode}`, type: "number", min: "0", max: "100", value: setting.score, onChange: e => handleChange('score', parseInt(e.target.value, 10) || 0), disabled: disabled, className: "w-16 rounded-md border border-border-subtle bg-surface-2 px-2 py-1 text-sm text-text-primary focus:outline-none focus:ring-1 focus:ring-accent-primary/50 disabled:cursor-not-allowed disabled:opacity-50", "aria-label": `${setting.languageCode} score` })] }), _jsx("button", { type: "button", onClick: onRemove, disabled: disabled, className: "rounded-md p-1.5 text-text-muted transition-colors hover:bg-surface-2 hover:text-accent-danger disabled:cursor-not-allowed disabled:opacity-50", "aria-label": `Remove ${setting.languageCode}`, children: _jsx(Trash2, { className: "h-4 w-4" }) })] }));
}
//# sourceMappingURL=LanguageSettingRow.js.map